Добрый день!
Lidia128/Homework3.3 pull request #1
Opened 2022-12-18 10:22 UTC by Lidia128

Написала программу, но файл в котором я могу вносить данне не такой как на видео. Что-то не так делаю, но не могу понять что. Помогите пожалуйста разобраться.

2022-12-18 10:37 UTC, DmitryN10 commented on src/main/java/me/recipe/homework/controller/IngredientController.java
> +    }
@GetMapping
    public Collection<Ingredient> getAllIngredient() {
        return ingredientService.getAll();
    }

2022-12-18 10:38 UTC, DmitryN10 commented on src/main/java/me/recipe/homework/controller/IngredientController.java
> +    }
не хвататет такого метода

2022-12-18 10:38 UTC, DmitryN10 commented on src/main/java/me/recipe/homework/controller/RecipeController.java
> +    private final RecipeService recipeService;
@GetMapping
    public Collection<Recipe> getAllRecipe() {
        return recipeService.getAll();
    }

2022-12-18 10:39 UTC, DmitryN10 commented on src/main/java/me/recipe/homework/service/IngredientService.java
> +public class IngredientService {
стоило под каждый сервис также создать интерфейс

2022-12-22 07:03 UTC, OlgaLugacheva requested changes

2022-12-22 07:03 UTC, OlgaLugacheva commented on src/main/java/me/recipe/homework/controller/RecipeController.java
> +    public ResponseEntity<Recipe> editRecipe(@PathVariable long id, @RequestBody Recipe recipe) {
в карте у вас Integer - тогда и зедсь тип id должен быть Integer

2022-12-22 07:03 UTC, OlgaLugacheva commented on src/main/java/me/recipe/homework/impl/RecipeServiceImpl.java
> +    public Recipe editRecipe(long id, Recipe recipe) {
Здесь тоже используйте Integer

2022-12-22 07:03 UTC, OlgaLugacheva commented on src/main/java/me/recipe/homework/controller/RecipeController.java
> +        Recipe recipe = recipeService.editRecipe(id, recipe);
определите новую пеерменную 
 Recipe updatedRecipe = recipeService.editRecipe(id, recipe);

2022-12-25 18:47 UTC, OlgaLugacheva requested changes

2022-12-25 18:47 UTC, OlgaLugacheva commented on src/main/java/me/recipe/homework/controller/RecipeController.java
>              return ResponseEntity.notFound().build();
в респонс тогда тоже нужно updatedReceipe

2022-12-25 19:18 UTC, merged